version: "3.1"

services:
  mariadb:
    image: "mariadb"
    networks:
      - no-internet
      - internet
    ports:
      - "3306:3306"

  node:
    build: .
    networks:
      - no-internet
    environment:
      ENVIRONMENT: production
      DB_HOST: mariadb
      DATABASE: dungeon
      REDIS_HOST: redis
    ports:
      - "8080:8080"

  nginx:
    build: ./nginx
    networks:
      - no-internet
      - internet
    depends_on:
      - node
    ports:
      - "80:8282"

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
