version: '2'

services:

  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=timeline
    ports:
      - '3306:3306'

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  node:
    build: .
    ports:
      - "8080:8080"

