version: '2'

services:
  # This MariaDB container can be used as development database
  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=timeline
    ports:
      - '3306:3306'

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  node_install:
    image: "BASE"

  node_base:
    image: "INSTALL"
    depends_on: 
      - "node_install"

  node:
    image: "SERVER"
    depends_on: 
      - "node_base"
    ports:
      - "8080:8080"

