version: '3.1'

services:

  mariadb:
    image: "mariadb"
    networks:
      - no-internet
    ports:
      - '3306:3306'

  redis:
    image: "redis:alpine"
    networks:
      - no-internet
    ports:
      - "6379:6379"

  node:
    build: .
    networks:
      - no-internet
    environment:
      ENVIRONMENT: production
      DB_HOST: mariadb
      DATABASE: dungeon
      REDIS_HOST: redis
    ports:
      - "8080:8080"

  nginx:
    build: ./nginx
    networks:
      - no-internet
      - internet
    depends_on:
      - node
    ports:
      - '8282:8282'


networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
