version: "3.1"

services:
  mariadb:
    image: "mariadb"
    networks:
      - no-internet
      - internet
    ports:
      - "3306:3306"

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
